# This workflow is to understand some of the GitHub action capabilities
name: experiment
on:
  workflow_dispatch:
    inputs:
      created:
        description: "created parameter of https://docs.github.com/en/rest/reference/actions#list-workflow-runs--parameters"
        # required: true
        # ${{ github.event.inputs.created }}

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          export TODAY=$(date +'%Y-%m-%d')
          echo $TODAY
          echo ${CREATED:-$TODAY}
        env:
          CREATED: ${{ github.event.inputs.created }} 
