# This workflow is to understand some of the GitHub action capabilities
name: experiment
on:
  workflow_dispatch:
    created:
      description: "created parameter of https://docs.github.com/en/rest/reference/actions#list-workflow-runs--parameters"
      # required: true
      # ${{ github.event.inputs.created }}

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.input.created }}
